### ISSUE TITLE
what do i do ?????

### ISSUE THREAD

**Issue by PedaretKhor** [skidghoul/BongoTokenGenerator#3]
5vX5ka-ujsLFFT42W-
[@] Generator Started -------------------------

Exception in thread Thread-1 (start):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\pj\BongoTokenGenerator-main\main.py", line 347, in start
    Discord().create_token(invite_code = invite_code, username = 'BongoGen | %s' % ''.join(random.choice(string.ascii_letters) for x in range(3)), DISCORD_WEBHOOK_URL = webhook, email = '')
  File "C:\Users\User\Desktop\pj\BongoTokenGenerator-main\main.py", line 230, in create_token
    task_id            = captcha.create_task()
  File "C:\Users\User\Desktop\pj\BongoTokenGenerator-main\main.py", line 36, in create_task
    return self.solver.create_task(
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\capmonster_python\hcaptcha.py", line 36, in create_task
    return self._make_request("createTask", data).get("taskId")
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\capmonster_python\utils.py", line 24, in wrap
    raise CapmonsterException(error_id=rf.get("errorId"),
capmonster_python.utils.CapmonsterException: [ERROR_ZERO_BALANCE] Account has zero balance

**Comment by skidghoul** [comment]
You need money on your capmonster in order to run.
