### ISSUE TITLE
Traceback (most recent call last):   File "/home/aomayan24/BongoTokenGenerator/main.py", line 11, in <module>     class Settings():   File "/home/aomayan24/BongoTokenGenerator/main.py", line 13, in Settings     'CAPTCHA_KEY'    : CAPTCHA_KEY or os.environ['CAPTCHA_KEY'] or '',   File "/usr/lib/python3.9/os.py", line 679, in __getitem__     raise KeyError(key) from None KeyError: 'CAPTCHA_KEY'

### ISSUE THREAD

**Issue by Aomayan24** [skidghoul/BongoTokenGenerator#4]
help

**Comment by skidghoul** [comment]
Are you using replit? If so, you have to create a key named "CAPTCHA_KEY" directly from the secrets tab.
